/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comprobarrefuerzo;


import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;


/**
 *
 * @author Antonio
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    Programa programa= new Programa(this);
    private boolean selected_anhadir=false;
    private boolean selected_salir=false;
    File folder = new File("./Datos");
    File ficheroRefuerzo=new File("Datos/Contratos refuerzo.obj");
    File ficheroVacaciones=new File("Datos/Contratos vacaxiones.obj");
    File ficheroBajas=new File("Datos/Contratos Bajas.obj");
    /**
     * Creates new form VentanaPrincipal1
     */
    public VentanaPrincipal() {
        initComponents();
        folder.mkdir();
        this.diaConsultaRefuerzo.setVisible(false);
        this.MesConsultaRefuerzo.setVisible(false);
        this.anhoConsultaRefuerzo.setVisible(false);
        try {
            programa.leeDatos(ficheroRefuerzo,ficheroVacaciones,ficheroBajas);
            programa.imprimirDatosPaneles();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        programa.imprimirTiempoTrabajado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeleccionCalculoRefuerzo = new javax.swing.ButtonGroup();
        TipoContratos = new javax.swing.ButtonGroup();
        ContratoNuevo = new javax.swing.JPanel();
        dia_comienzo = new javax.swing.JComboBox();
        mes_comienzo = new javax.swing.JComboBox();
        anho_comienzo = new javax.swing.JTextField();
        dia_finalizacion = new javax.swing.JComboBox();
        mes_finalizacion = new javax.swing.JComboBox();
        anho_finalizacion = new javax.swing.JTextField();
        ahnadir = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        TipoContratoRefuerzo = new javax.swing.JCheckBox();
        TipoContratoVacaciones = new javax.swing.JCheckBox();
        TipoContratoBaja = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        PanelContratosRefuerzo = new javax.swing.JTextArea();
        jPanelCalcularRefuerzo = new javax.swing.JPanel();
        RefuerzoFechaAuto = new javax.swing.JRadioButton();
        RefuerzoFechaManual = new javax.swing.JRadioButton();
        anhoConsultaRefuerzo = new javax.swing.JTextField();
        MesConsultaRefuerzo = new javax.swing.JComboBox();
        diaConsultaRefuerzo = new javax.swing.JComboBox();
        ConsultarRefuerzo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTiempoRefuerzo = new javax.swing.JTextArea();
        jExit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        PanelContratosVacaciones = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        PanelContratosBajas = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTiempoTrabajadoCorreos = new javax.swing.JTextArea();
        EliminarContratos = new javax.swing.JPanel();
        dia_comienzo_eliminar = new javax.swing.JComboBox();
        mes_comienzo_eliminar = new javax.swing.JComboBox();
        anho_comienzo_eliminar = new javax.swing.JTextField();
        dia_finalizacion_eliminar = new javax.swing.JComboBox();
        mes_finalizacion_eliminar = new javax.swing.JComboBox();
        anho_finalizacion_eliminar = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        JEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JAyuda = new javax.swing.JButton();
        jReiniciar = new javax.swing.JToggleButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcular tiempo de refuerzo");
        setBackground(new java.awt.Color(102, 102, 255));

        ContratoNuevo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contratos Antiguos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));

        dia_comienzo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mes_comienzo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        mes_comienzo.setSelectedItem(mes_comienzo);

        anho_comienzo.setPreferredSize(new java.awt.Dimension(60, 20));

        dia_finalizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mes_finalizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        anho_finalizacion.setPreferredSize(new java.awt.Dimension(60, 20));

        ahnadir.setText("Añadir contrato");
        ahnadir.addMouseListener(formListener);

        jTextField1.setText("Fecha de inicio del contrato");

        jTextField2.setText("Fecha de finalización de contrato");

        TipoContratos.add(TipoContratoRefuerzo);
        TipoContratoRefuerzo.setText("Refuerzo");

        TipoContratos.add(TipoContratoVacaciones);
        TipoContratoVacaciones.setText("Vacaciones");

        TipoContratos.add(TipoContratoBaja);
        TipoContratoBaja.setText("Baja");

        javax.swing.GroupLayout ContratoNuevoLayout = new javax.swing.GroupLayout(ContratoNuevo);
        ContratoNuevo.setLayout(ContratoNuevoLayout);
        ContratoNuevoLayout.setHorizontalGroup(
            ContratoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratoNuevoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ContratoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContratoNuevoLayout.createSequentialGroup()
                        .addComponent(dia_finalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mes_finalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anho_finalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TipoContratoBaja))
                    .addGroup(ContratoNuevoLayout.createSequentialGroup()
                        .addGroup(ContratoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContratoNuevoLayout.createSequentialGroup()
                                .addComponent(dia_comienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(mes_comienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anho_comienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ContratoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipoContratoVacaciones)
                            .addComponent(TipoContratoRefuerzo)))
                    .addGroup(ContratoNuevoLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(ahnadir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContratoNuevoLayout.setVerticalGroup(
            ContratoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContratoNuevoLayout.createSequentialGroup()
                .addGroup(ContratoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContratoNuevoLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContratoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dia_comienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContratoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mes_comienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(anho_comienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContratoNuevoLayout.createSequentialGroup()
                        .addComponent(TipoContratoRefuerzo)
                        .addGap(11, 11, 11)))
                .addGroup(ContratoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoContratoVacaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(ContratoNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dia_finalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes_finalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anho_finalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoContratoBaja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ahnadir))
        );

        PanelContratosRefuerzo.setColumns(20);
        PanelContratosRefuerzo.setRows(5);
        PanelContratosRefuerzo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contratos Refuerzo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));
        jScrollPane2.setViewportView(PanelContratosRefuerzo);

        SeleccionCalculoRefuerzo.add(RefuerzoFechaAuto);
        RefuerzoFechaAuto.setText("Meses de refuerzo hasta fecha de hoy");
        RefuerzoFechaAuto.addMouseListener(formListener);

        SeleccionCalculoRefuerzo.add(RefuerzoFechaManual);
        RefuerzoFechaManual.setText("Introducir la fecha de consulta");
        RefuerzoFechaManual.addMouseListener(formListener);

        anhoConsultaRefuerzo.setPreferredSize(new java.awt.Dimension(60, 20));

        MesConsultaRefuerzo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        diaConsultaRefuerzo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        ConsultarRefuerzo.setText("Consultar Refuerzo");
        ConsultarRefuerzo.addActionListener(formListener);

        javax.swing.GroupLayout jPanelCalcularRefuerzoLayout = new javax.swing.GroupLayout(jPanelCalcularRefuerzo);
        jPanelCalcularRefuerzo.setLayout(jPanelCalcularRefuerzoLayout);
        jPanelCalcularRefuerzoLayout.setHorizontalGroup(
            jPanelCalcularRefuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalcularRefuerzoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCalcularRefuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RefuerzoFechaAuto)
                    .addComponent(ConsultarRefuerzo)
                    .addGroup(jPanelCalcularRefuerzoLayout.createSequentialGroup()
                        .addComponent(RefuerzoFechaManual)
                        .addGap(35, 35, 35)
                        .addComponent(diaConsultaRefuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MesConsultaRefuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(anhoConsultaRefuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanelCalcularRefuerzoLayout.setVerticalGroup(
            jPanelCalcularRefuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalcularRefuerzoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RefuerzoFechaAuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCalcularRefuerzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RefuerzoFechaManual)
                    .addComponent(diaConsultaRefuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MesConsultaRefuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anhoConsultaRefuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(ConsultarRefuerzo)
                .addContainerGap())
        );

        jTiempoRefuerzo.setColumns(20);
        jTiempoRefuerzo.setRows(5);
        jTiempoRefuerzo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tiempo de refuerzo trabajado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));
        jScrollPane1.setViewportView(jTiempoRefuerzo);

        jExit.setText("Salir");
        jExit.addActionListener(formListener);

        PanelContratosVacaciones.setColumns(20);
        PanelContratosVacaciones.setRows(5);
        PanelContratosVacaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contratos Vacaciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));
        jScrollPane3.setViewportView(PanelContratosVacaciones);

        PanelContratosBajas.setColumns(20);
        PanelContratosBajas.setRows(5);
        PanelContratosBajas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contratos Bajas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));
        jScrollPane4.setViewportView(PanelContratosBajas);

        jTiempoTrabajadoCorreos.setColumns(20);
        jTiempoTrabajadoCorreos.setRows(5);
        jTiempoTrabajadoCorreos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tiempo trabajado en correos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));
        jScrollPane5.setViewportView(jTiempoTrabajadoCorreos);

        EliminarContratos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EliminarContrato", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));

        dia_comienzo_eliminar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mes_comienzo_eliminar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        mes_comienzo_eliminar.setSelectedItem(mes_comienzo);

        anho_comienzo_eliminar.setPreferredSize(new java.awt.Dimension(60, 20));

        dia_finalizacion_eliminar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mes_finalizacion_eliminar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        anho_finalizacion_eliminar.setPreferredSize(new java.awt.Dimension(60, 20));

        jTextField5.setText("Fecha de inicio del contrato");

        jTextField6.setText("Fecha de finalización de contrato");

        JEliminar.setText("Eliminar");
        JEliminar.addActionListener(formListener);

        javax.swing.GroupLayout EliminarContratosLayout = new javax.swing.GroupLayout(EliminarContratos);
        EliminarContratos.setLayout(EliminarContratosLayout);
        EliminarContratosLayout.setHorizontalGroup(
            EliminarContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarContratosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(EliminarContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EliminarContratosLayout.createSequentialGroup()
                        .addGroup(EliminarContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JEliminar)
                            .addGroup(EliminarContratosLayout.createSequentialGroup()
                                .addComponent(dia_finalizacion_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mes_finalizacion_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anho_finalizacion_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EliminarContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EliminarContratosLayout.createSequentialGroup()
                            .addComponent(dia_comienzo_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(mes_comienzo_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(anho_comienzo_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        EliminarContratosLayout.setVerticalGroup(
            EliminarContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarContratosLayout.createSequentialGroup()
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EliminarContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dia_comienzo_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EliminarContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mes_comienzo_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(anho_comienzo_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(EliminarContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dia_finalizacion_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes_finalizacion_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anho_finalizacion_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JEliminar))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BUZON CORREOS MEAO.jpg"))); // NOI18N

        JAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ayuda.png"))); // NOI18N
        JAyuda.setBorder(null);
        JAyuda.setMargin(new java.awt.Insets(0, 0, 0, 0));
        JAyuda.setPreferredSize(new java.awt.Dimension(30, 30));
        JAyuda.addActionListener(formListener);

        jReiniciar.setText("Reiniciar");
        jReiniciar.addActionListener(formListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jPanelCalcularRefuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ContratoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(EliminarContratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jReiniciar)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ContratoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EliminarContratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCalcularRefuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jExit)
                    .addComponent(jReiniciar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == ConsultarRefuerzo) {
                VentanaPrincipal.this.ConsultarRefuerzoActionPerformed(evt);
            }
            else if (evt.getSource() == jExit) {
                VentanaPrincipal.this.jExitActionPerformed(evt);
            }
            else if (evt.getSource() == JEliminar) {
                VentanaPrincipal.this.JEliminarActionPerformed(evt);
            }
            else if (evt.getSource() == JAyuda) {
                VentanaPrincipal.this.JAyudaActionPerformed(evt);
            }
            else if (evt.getSource() == jReiniciar) {
                VentanaPrincipal.this.jReiniciarActionPerformed(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == ahnadir) {
                VentanaPrincipal.this.ahnadirMouseClicked(evt);
            }
            else if (evt.getSource() == RefuerzoFechaAuto) {
                VentanaPrincipal.this.RefuerzoFechaAutoMouseClicked(evt);
            }
            else if (evt.getSource() == RefuerzoFechaManual) {
                VentanaPrincipal.this.RefuerzoFechaManualMouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void ahnadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ahnadirMouseClicked
        int diaComienzo= Integer.parseInt(dia_comienzo.getSelectedItem().toString());
        int diaFinalizacion=Integer.parseInt(dia_finalizacion.getSelectedItem().toString());
        String mesComienzo=mes_comienzo.getSelectedItem().toString();
        String mesFinalizacion=mes_finalizacion.getSelectedItem().toString();
        if(programa.sePuedeAnhadir(diaComienzo,diaFinalizacion,mesComienzo,mesFinalizacion,anho_comienzo.getText() , anho_finalizacion.getText()) 
                && programa.comprobarDiaSegunMes(diaFinalizacion, programa.obtenerNumeroMes(mesFinalizacion), Integer.parseInt(anho_finalizacion.getText()))
                &&programa.comprobarDiaSegunMes(diaComienzo, programa.obtenerNumeroMes(mesComienzo), Integer.parseInt(anho_comienzo.getText()))){
                int numeroTipoContrato=0;
                Contrato contrato= new Contrato(diaComienzo,diaFinalizacion, mesComienzo, mesFinalizacion,anho_comienzo.getText() , anho_finalizacion.getText());
                if (this.TipoContratoRefuerzo.isSelected() && programa.BuscarRepetidos(contrato).getFirst()==false ){
                    ficheroRefuerzo.delete();
                    numeroTipoContrato=1;
                    programa.setContrato(numeroTipoContrato, contrato, ficheroRefuerzo);
                       
                }else if(this.TipoContratoVacaciones.isSelected() && programa.BuscarRepetidos(contrato).getFirst()==false){
                    ficheroVacaciones.delete();
                    numeroTipoContrato=2;
                    programa.setContrato(numeroTipoContrato, contrato, ficheroVacaciones);
                }else if(this.TipoContratoBaja.isSelected() && programa.BuscarRepetidos(contrato).getFirst()==false){
                    ficheroBajas.delete();
                    numeroTipoContrato=3;
                    programa.setContrato(numeroTipoContrato, contrato, ficheroBajas);
                }else
                    new ErrorIntroduccionTipoContrato(this , true ).setVisible(true);   
        }else
            new ErrorIntroduccionDatos(this , true ).setVisible(true);      
        programa.Ordenar();
        programa.imprimirDatosPaneles();
        programa.imprimirTiempoTrabajado();
        repaint();
    }//GEN-LAST:event_ahnadirMouseClicked
    
    
    private void RefuerzoFechaManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefuerzoFechaManualMouseClicked
         diaConsultaRefuerzo.setVisible(true);
         MesConsultaRefuerzo.setVisible(true);
         anhoConsultaRefuerzo.setVisible(true);
    }//GEN-LAST:event_RefuerzoFechaManualMouseClicked

    private void RefuerzoFechaAutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefuerzoFechaAutoMouseClicked
        diaConsultaRefuerzo.setVisible(false);
        MesConsultaRefuerzo.setVisible(false);
        anhoConsultaRefuerzo.setVisible(false);
    }//GEN-LAST:event_RefuerzoFechaAutoMouseClicked

    private void ConsultarRefuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarRefuerzoActionPerformed
        Pair<Pair<Integer,Integer>,Integer> refuerzoTrabajado= new Pair();
        this.jTiempoRefuerzo.setText(null);
        if(this.RefuerzoFechaManual.isSelected()){
            if(anhoConsultaRefuerzo.getText().isEmpty()==false ){
                this.anhoConsultaRefuerzo.setVisible(true);
                this.diaConsultaRefuerzo.setVisible(true);
                this.MesConsultaRefuerzo.setVisible(true);
                refuerzoTrabajado=programa.numeroMesesRefuerzo(diaConsultaRefuerzo.getSelectedIndex()+1, programa.obtenerNumeroMes(MesConsultaRefuerzo.getSelectedItem().toString()),Integer.parseInt(anhoConsultaRefuerzo.getText()));
                this.jTiempoRefuerzo.setText(null);
                this.jTiempoRefuerzo.append("Tienes "+  refuerzoTrabajado.getFirst().getFirst() + " dias y " + refuerzoTrabajado.getFirst().getSecond() + " meses y "
                         + refuerzoTrabajado.getSecond() +" años\n");
            }else{
                new ErrorIntroduccionTipoContrato(this , true ).setVisible(true);
            }  
        }else if(this.RefuerzoFechaAuto.isSelected()){
            refuerzoTrabajado=programa.numeroMesesRefuerzo();
            this.jTiempoRefuerzo.setText(null);
            this.jTiempoRefuerzo.append("Tienes "+  refuerzoTrabajado.getFirst().getFirst() + " dias y " + refuerzoTrabajado.getFirst().getSecond() + " meses y "
                         + refuerzoTrabajado.getSecond() +" años\n");
        }
    }//GEN-LAST:event_ConsultarRefuerzoActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jExitActionPerformed

    private void jReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReiniciarActionPerformed
        ficheroRefuerzo.delete();
        ficheroVacaciones.delete();
        ficheroBajas.delete();
        this.PanelContratosBajas.setText(null);
        this.PanelContratosRefuerzo.setText(null);
        this.PanelContratosVacaciones.setText(null);
        this.jTiempoRefuerzo.setText(null);
        this.jTiempoRefuerzo.setText(null);
        programa.reiniciar();
        this.jTiempoTrabajadoCorreos.setText(null);
    }//GEN-LAST:event_jReiniciarActionPerformed

    private void JEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEliminarActionPerformed
        int diaComienzo= this.dia_comienzo_eliminar.getSelectedIndex()+1;
        int diaFinalizacion=dia_finalizacion_eliminar.getSelectedIndex()+1;
        String mesComienzo=mes_comienzo_eliminar.getSelectedItem().toString();
        String mesFinalizacion=mes_finalizacion_eliminar.getSelectedItem().toString();
        Contrato contrato= new Contrato(diaComienzo,diaFinalizacion, mesComienzo, mesFinalizacion,anho_comienzo_eliminar.getText() , anho_finalizacion_eliminar.getText());
        int tipoContrato=0;
        if(programa.BuscarRepetidos(contrato).getFirst()){
            tipoContrato=programa.BuscarRepetidos(contrato).getSecond();
            if(tipoContrato==1){
                ficheroRefuerzo.delete();
                programa.Eliminar(tipoContrato, contrato);
                try {
                    programa.guardaDatos(tipoContrato,ficheroRefuerzo);
                } catch (IOException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if (tipoContrato==2){
                ficheroVacaciones.delete();
                programa.Eliminar(tipoContrato, contrato);
                try {
                    programa.guardaDatos(tipoContrato,ficheroVacaciones);
                } catch (IOException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if(tipoContrato==3){
                ficheroBajas.delete();
                programa.Eliminar(tipoContrato, contrato);
                try {
                    programa.guardaDatos(tipoContrato,ficheroBajas);
                } catch (IOException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else
            new ErrorEliminarContrato(this , true ).setVisible(true);
        programa.imprimirDatosPaneles();
        programa.imprimirTiempoTrabajado();
    }//GEN-LAST:event_JEliminarActionPerformed

    private void JAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAyudaActionPerformed
        new Ayuda(this , true ).setVisible(true);
    }//GEN-LAST:event_JAyudaActionPerformed
                                   

   public boolean isSelectedAnhadir(){
        return selected_anhadir;
    }
   public boolean isSelectedSalir(){
        return selected_salir;
    }
   public JTextArea getPanelContratosRefuerzo(){
       return this.PanelContratosRefuerzo;
   }
   public JTextArea getPanelContratosVacaciones(){
       return this.PanelContratosVacaciones;
   }
   public JTextArea getPanelContratosBajas(){
       return this.PanelContratosBajas;
   }
   public JTextArea getPanelTiempotrabajado(){
       return this.jTiempoTrabajadoCorreos;
   } 
   public int tipoContratoSeleccionado(){
       int tipoContrato=0;
       if(TipoContratoRefuerzo.isSelected())
           tipoContrato=1;
       else if(TipoContratoVacaciones.isSelected())
           tipoContrato=2;
       else if(TipoContratoBaja.isSelected())
           tipoContrato=3;
       return tipoContrato;
   } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarRefuerzo;
    private javax.swing.JPanel ContratoNuevo;
    private javax.swing.JPanel EliminarContratos;
    private javax.swing.JButton JAyuda;
    private javax.swing.JButton JEliminar;
    private javax.swing.JComboBox MesConsultaRefuerzo;
    private javax.swing.JTextArea PanelContratosBajas;
    private javax.swing.JTextArea PanelContratosRefuerzo;
    private javax.swing.JTextArea PanelContratosVacaciones;
    private javax.swing.JRadioButton RefuerzoFechaAuto;
    private javax.swing.JRadioButton RefuerzoFechaManual;
    private javax.swing.ButtonGroup SeleccionCalculoRefuerzo;
    private javax.swing.JCheckBox TipoContratoBaja;
    private javax.swing.JCheckBox TipoContratoRefuerzo;
    private javax.swing.JCheckBox TipoContratoVacaciones;
    private javax.swing.ButtonGroup TipoContratos;
    private javax.swing.JButton ahnadir;
    private javax.swing.JTextField anhoConsultaRefuerzo;
    private javax.swing.JTextField anho_comienzo;
    private javax.swing.JTextField anho_comienzo_eliminar;
    private javax.swing.JTextField anho_finalizacion;
    private javax.swing.JTextField anho_finalizacion_eliminar;
    private javax.swing.JComboBox diaConsultaRefuerzo;
    private javax.swing.JComboBox dia_comienzo;
    private javax.swing.JComboBox dia_comienzo_eliminar;
    private javax.swing.JComboBox dia_finalizacion;
    private javax.swing.JComboBox dia_finalizacion_eliminar;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelCalcularRefuerzo;
    private javax.swing.JToggleButton jReiniciar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextArea jTiempoRefuerzo;
    private javax.swing.JTextArea jTiempoTrabajadoCorreos;
    private javax.swing.JComboBox mes_comienzo;
    private javax.swing.JComboBox mes_comienzo_eliminar;
    private javax.swing.JComboBox mes_finalizacion;
    private javax.swing.JComboBox mes_finalizacion_eliminar;
    // End of variables declaration//GEN-END:variables
}
